### ISSUE TITLE
Make it possible to pass in an element reference instead of a css selector

### ISSUE THREAD

**Issue by Windvis** [zestia/ember-simple-infinite-scroller#12]
Modifiers make it easy to get access to an element's reference, so it would be nice if those could be passed in as well, instead of having to add a class / data attribute purely to find the element in the dom.

**Comment by amk221** [comment]
Currently the you can provide a selector, and the element found by that selector will always be a child of the component. 

If you could pass in an element, then that element could have come from anywhere. It wouldn't make sense to monitor an element outside of the infinite scroller itself.

So if I was to implement this, I'd have to add a guard to make sure the element passed in was indeed a child.

Can you mark up an example of how you would like to see this work (hbs). Cheers
