### ISSUE TITLE
scroller.isLoading not working (could be a user issue)

### ISSUE THREAD

**Issue by Mithrilhall** [zestia/ember-simple-infinite-scroller#13]
The line `{{log scroller}}` below produces the following in dev tools on the first call:
`EmptyObject {error: null, isScrollable: undefined, isLoading: false, loadMore: ƒ}`
and this on each additional call:
`EmptyObject {error: null, isScrollable: false, isLoading: false, loadMore: ƒ}`

My action 'loadMore' is on my controller and updates my model after making a new fetch.
```
{{#infinite-scroller useDocument=true onLoadMore=(action "loadMore") as |scroller|}} 
  {{#each model.groupedPosts as |group index|}}
    {{blog/post-card group=group index=index length=postsLength}}
  {{/each}}
  {{log scroller}}
  {{#if scroller.isLoading}}
    <script>
      document.body.style.background = "red";
    </script>
  {{/if}}
{{/infinite-scroller}}

**Comment by amk221** [comment]
👋I _think_ it's probably be a user issue. What does your `loadMore` action look like?

`scroller.isLoading` will only be true for the length of time it takes for `loadMore` to settle (assuming it returns a promise).

In the meantime, I will update the documentation to make this more clear!

**Comment by Mithrilhall** [comment]
Something like this:
```
loadMore() {
      if (this.model.posts.length < this.model.meta.pagination.total) {
        fetch(`https://<blog>.ghost.io/ghost/api/v2/content/posts/?key=<key>&include=tags&limit=10&page=${this.page++}`).then(response => {
          return response.json();
        }).then(data => {
          let model = this.model;
          let posts = model.posts;
          posts = posts.concat(data.posts);
          set(model, 'posts', posts);
        })
      }
    }
  }

**Comment by amk221** [comment]
Ok, thanks. Looks like `loadMore` doesn't have a return value. (It should return a "promise that more will be loaded")

So if you change it to: `return fetch...`, then the InfiniteScroller component will know when your work is done.

**Comment by Mithrilhall** [comment]
User error indeed. Thanks....that worked perfectly.
