### ISSUE TITLE
There is no information regarding tests

### ISSUE THREAD

**Issue by takshch** [zestia/ember-simple-infinite-scroller#17]
# Description
There is no information given on testing of the InfiniteScroller component in the description.

**Comment by amk221** [comment]
Fair point!

I will see if I can expose the test helpers I use internally, and document them so you can use them too

**Comment by amk221** [comment]
Is this ok?

https://github.com/zestia/ember-simple-infinite-scroller/pull/18

**Comment by takshch** [comment]
@amk221 It's okay but we should also have helper for checking scrollability of the scrollbar.

**Comment by amk221** [comment]
For that you can use 

```
assert.dom('.infinite-scroller').hasClass('infinite-scroller--scrollable')
```
