### ISSUE TITLE
Cannot read property 'scrollTop' of undefined

### ISSUE THREAD

**Issue by MuditBatheja** [zestia/ember-simple-infinite-scroller#7]
Going to the new route. Shows "Cannot read property 'scrollTop' of undefined". Is there any way to destroy component while transition to new route?

**Comment by amk221** [comment]
Hi, are you using the latest version? The component (and scroll listeners) should be torn down automatically.

**Comment by MuditBatheja** [comment]
I am using version 1.0.12. Thanks for quick reply

**Comment by amk221** [comment]
Thanks, I think you should be able to upgrade to 1.0.20 without any problems. Could you try that first?

**Comment by MuditBatheja** [comment]
It worked!! Thanks. Can you publish the latest version on yarn also?

**Comment by amk221** [comment]
🤔 ok, is the project public / would you be able to share any details about how you are using it? / what attributes you are sending in etc. thanks!

**Comment by MuditBatheja** [comment]
I am using in a component and passing use-document and trigger on only.. while transitioning to new route. It's still checking for scroll position. I tried with latest and old but it is checking for the this._element().

**Comment by amk221** [comment]
I'm sorry, I don't know how this could be?
There is a test to prevent this from happening:
https://github.com/zestia/ember-simple-infinite-scroller/commit/318ce30f799ad9ce4194060acb9e6953a82a2ff7#diff-7347d90d1b9c5ec2bd58b40f07dac8ba

Could you let me know what version of Ember you are on? thanks

**Comment by amk221** [comment]
Hi? Are you still experiencing a problem

**Comment by MuditBatheja** [comment]
Yes, I manually tear down listener. It start working for me. Thanks.
